[var.GHO_spot_settings]
synth_gho_max_collateral_amount = "<%= parseEther(String(10_000_000)) %>"
synth_gho_skew_scale = "<%= 1 %>"                                         #1 wei

[invoke.SpotMarketProxy_createSynth_GHO]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "owner"
func = "createSynth"
args = ["Synthetic GHO", "sGHO", "<%= settings.pdao %>"]
extra.synth_gho_market_id.event = "SynthRegistered"
extra.synth_gho_market_id.arg = 0
extra.synth_gho_token_address.event = "SynthRegistered"
extra.synth_gho_token_address.arg = 1

[invoke.SpotMarketProxy_updatePriceData_GHO]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_gho_market_id %>"]
func = "updatePriceData"
args = [
    "<%= extras.synth_gho_market_id %>",
    "<%= extras.gho_oracle_id %>",
    "<%= extras.gho_oracle_id %>",
    "<%= settings.big_cap_strict_staleness_tolerance %>",
]

[invoke.CoreProxy_configureMaximumMarketCollateral_GHO]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= extras.synth_gho_market_id %>",
    "<%= settings.gho_address %>",
    "<%= settings.synth_gho_max_collateral_amount %>",
]

[invoke.SpotMarketProxy_setWrapper_GHO]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_gho_market_id %>"]
func = "setWrapper"
args = [
    "<%= extras.synth_gho_market_id %>",
    "<%= settings.gho_address %>",
    "<%= settings.synth_gho_max_collateral_amount %>",
]

[invoke.SpotMarketProxy_addSettlementStrategy_GHO]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_gho_market_id %>"]
func = "addSettlementStrategy"
args = [
    "<%= extras.synth_gho_market_id %>",
    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", url = "", settlementReward = 0, minimumUsdExchangeAmount = "0", maxRoundingLoss = "1", priceDeviationTolerance = "0", disabled = false },
]
extra.synth_gho_settlement_strategy_id.event = "SettlementStrategyAdded"
extra.synth_gho_settlement_strategy_id.arg = 1

[invoke.SpotMarketProxy_setSettlementStrategy_GHO]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_gho_market_id %>"]
func = "setSettlementStrategy"
args = [
    "<%= extras.synth_gho_market_id %>",
    "<%= extras.synth_gho_settlement_strategy_id %>",
    { strategyType = "0", settlementDelay = "<%= settings.big_cap_settlement_delay %>", settlementWindowDuration = "<%= settings.big_cap_settlement_window_duration %>", priceVerificationContract = "<%= settings.gho_aggregator_address %>", feedId = "<%= formatBytes32String('gho') %>", url = "<%= `url` %>", settlementReward = "<%= settings.settlement_reward %>", minimumUsdExchangeAmount = "<%= settings.settlement_minimum_usd_exchange_amount %>", maxRoundingLoss = "<%= settings.settlement_max_rounding_loss %>", priceDeviationTolerance = "<%= settings.price_deviation_tolerance %>", disabled = true },
]

[invoke.SpotMarketProxy_setAtomicFixedFee_GHO]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_gho_market_id %>"]
func = "setAtomicFixedFee"
args = ["<%= extras.synth_gho_market_id %>", "<%= parseEther(String(0.30)) %>"]
