[var.perps_collateral_gho_settings]
synth_gho_upper_limit_discount = "<%= parseEther('0.0051') %>"
synth_gho_lower_limit_discount = "<%= parseEther('0.0050') %>"
synth_gho_discount_scalar = "<%= parseEther('1') %>"

[invoke.PerpsMarketProxy_setCollateralConfiguration_synth_gho]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setCollateralConfiguration"
args = [
    "<%= extras.synth_gho_market_id %>",
    "<%= settings.synth_gho_max_collateral_amount %>",
    "<%= settings.synth_gho_upper_limit_discount %>",
    "<%= settings.synth_gho_lower_limit_discount %>",
    "<%= settings.synth_gho_discount_scalar %>",
]

[invoke.CoreProxy_configureMaximumMarketCollateral_Perps_synth_gho]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= imports.perpsFactory.extras.superMarketId %>",
    "<%= extras.synth_gho_token_address %>",
    "<%= settings.synth_gho_max_collateral_amount %>",
]
