[provision.RewardsDistributor_SpartanCouncilPool_ARB_rewards_for_GHO_lp]
source = "synthetix-rewards-distributor:0.0.2"
target = "synthetix-rewards-distributor:0.0.2@ARB_rewards_for_GHO_lp"
options.salt = "<%= settings.salt %>"
options.rewardManager = "<%= imports.system.contracts.CoreProxy.address %>"
options.poolId = "<%= extras.spartan_council_pool_id %>"
options.collateralType = "<%= settings.gho_address %>"
options.payoutToken = "<%= settings.arb_address %>"
options.payoutTokenDecimals = "18"
options.name = "Spartan Council Pool ARB Rewards for GHO LP"

[invoke.CoreProxy_registerRewardsDistributor_SpartanCouncilPool_ARB_rewards_for_GHO_lp]
target = ["system.CoreProxy"]
fromCall.func = "getPoolOwner"
fromCall.args = ["<%= extras.spartan_council_pool_id %>"]
func = "registerRewardsDistributor"
args = [
    "<%= extras.spartan_council_pool_id %>",
    "<%= settings.gho_address %>",
    "<%= imports.RewardsDistributor_SpartanCouncilPool_ARB_rewards_for_GHO_lp.contracts.RewardsDistributor.address %>",
]
